// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migration'lar havuzlu (pooler) adres üzerinden ÇALIŞMAZ: PgBouncer'ın
    // transaction modunda şema kilidi (advisory lock) tutulamaz. Bu yüzden
    // burada doğrudan adres kullanılır; uygulama çalışırken ise havuzlu adres
    // (DATABASE_URL) kullanılır. DIRECT_URL yoksa eski davranışa düşer.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
